feature: функционал сервиса статистики
verazhadovskaya/java-explore-with-me pull request #1
Opened 2024-01-09 19:53 UTC by verazhadovskaya

2024-01-10 11:06 UTC, EugeneLenkevich requested changes
Привет, Вера, с наступившими, спасибо за PR  

В целом все отлично, только давай с датами разберемся, а то это не очень выглядит в строковом виде, диплом все таки :)

2024-01-10 11:06 UTC, EugeneLenkevich commented on stats/client/src/main/java/ru/practicum/WebClientConfig.java
> +        StatsClient client = new StatsClient(restTemplate);
`return new StatsClient(restTemplate);`

А может сразу вот так записать, покороче :)

2024-01-10 11:06 UTC, EugeneLenkevich commented on stats/server/src/main/java/ru/practicum/controller/StatsController.java
> +    public List<StatsView> get(@RequestParam(value = "start", required = true) String start,
```
@RequestParam(value = "start", required = true) String start,
@RequestParam(value = "end", required = true) String end
```

Кажется что лучше тут сразу использовать LocalDate как типы параметров чтобы потом не парсить строки.

PS
Если что можно попробовать настроить форматы даты и времени глобально, например как в статье ниже

https://www.baeldung.com/spring-boot-formatting-json-dates

2024-01-10 15:10 UTC, verazhadovskaya commented on stats/server/src/main/java/ru/practicum/controller/StatsController.java
> +    public List<StatsView> get(@RequestParam(value = "start", required = true) String start,
а у нас по ТЗ надо сделать как в сваггере, а в сваггере вот так
![Capture](https://github.com/verazhadovskaya/java-explore-with-me/assets/130570412/cdb53d11-3ba2-46f4-aa95-49f10442de3f)

2024-01-10 16:19 UTC, EugeneLenkevich commented on stats/server/src/main/java/ru/practicum/controller/StatsController.java
> +    public List<StatsView> get(@RequestParam(value = "start", required = true) String start,
А вроде в контроллере это не мешает даты указать как тип параметров, можно попробовать

2024-01-11 18:33 UTC, verazhadovskaya commented on stats/server/src/main/java/ru/practicum/controller/StatsController.java
> +    public List<StatsView> get(@RequestParam(value = "start", required = true) String start,
исправила

2024-01-11 18:33 UTC, verazhadovskaya commented on stats/client/src/main/java/ru/practicum/WebClientConfig.java
> +        StatsClient client = new StatsClient(restTemplate);
поменяла, спасибо

2024-01-12 05:08 UTC, EugeneLenkevich approved these changes
Все получилось, супер, спасибо :)

2024-01-12 07:29 UTC, merged